import type { ClimateFact, ClimateHazard, ClimateRisk } from "@/lib/climate-profile";

export type TermKind = "risk" | "fact" | "hazard";

export type VocabularyEntry = {
  id: ClimateRisk | ClimateFact | ClimateHazard;
  kind: TermKind;
  label: string;
  aliases: string[];
};

/**
 * Canonical climate / hazard vocabulary + natural-language aliases for the query parser.
 * Aliases are matched longest-first; keep multi-word phrases ahead of short tokens.
 */
export const CLIMATE_VOCABULARY: VocabularyEntry[] = [
  {
    id: "extreme_heat",
    kind: "risk",
    label: "extreme heat",
    aliases: [
      "extreme heat",
      "heat risk",
      "heat stress",
      "heatwave",
      "heat wave",
      "heat waves",
      "hot weather",
      "hottest",
      "very hot",
      "scorching",
      "sweltering",
      "blistering heat",
      "oppressive heat",
      "dangerous heat",
      "record heat",
      "high temperature",
      "high temperatures",
      "soaring temperatures",
      "hot summers",
      "summer heat",
      "urban heat",
      "heat island",
      "hot",
    ],
  },
  {
    id: "extreme_cold",
    kind: "risk",
    label: "extreme cold",
    aliases: [
      "extreme cold",
      "cold risk",
      "cold snap",
      "cold wave",
      "deep freeze",
      "hard freeze",
      "freezing",
      "frigid",
      "bitter cold",
      "arctic cold",
      "subzero",
      "sub-zero",
      "very cold",
      "coldest",
      "winter cold",
      "harsh winter",
      "low temperature",
      "low temperatures",
      "frost",
      "frostbite risk",
      "ice storm",
      "black ice",
      "blizzard",
      "snowstorm",
      "heavy snow",
      "snowfall",
      "snow",
      "sleet",
      "wintry mix",
      "ice",
      "cold",
    ],
  },
  {
    id: "heavy_rainfall",
    kind: "risk",
    label: "heavy rainfall",
    aliases: [
      "heavy rainfall",
      "heavy rain",
      "extreme rain",
      "extreme rainfall",
      "torrential rain",
      "torrential rainfall",
      "intense rainfall",
      "intense rain",
      "flood risk",
      "flooding",
      "floods",
      "flood",
      "flash flood",
      "flash floods",
      "river flood",
      "urban flood",
      "inland flood",
      "floodwaters",
      "flood water",
      "deluge",
      "downpour",
      "downpours",
      "cloudburst",
      "rainstorm",
      "rainstorms",
      "wettest",
      "high rainfall",
      "high precipitation",
      "heavy precipitation",
      "extreme precipitation",
      "precipitation extremes",
      "rainy",
      "rainfall",
      "rain",
      "precip",
      "precipitation",
      "wet",
      "soaking rains",
      "waterlogged",
    ],
  },
  {
    id: "drought_stress",
    kind: "risk",
    label: "drought stress",
    aliases: [
      "drought stress",
      "drought risk",
      "severe drought",
      "prolonged drought",
      "water stress",
      "water scarcity",
      "water shortage",
      "arid risk",
      "dry spell",
      "dry spells",
      "parched",
      "desiccation",
      "low rainfall",
      "low precipitation",
      "rain deficit",
      "rainfall deficit",
      "driest",
      "drought",
      "dry",
    ],
  },
  {
    id: "high_seasonality",
    kind: "risk",
    label: "high seasonality",
    aliases: [
      "high seasonality",
      "strong seasonality",
      "large temperature swing",
      "temperature swings",
      "temperature swing",
      "seasonal contrast",
      "four seasons",
      "strong seasons",
      "distinct seasons",
      "continental seasons",
      "seasonality",
      "seasonal",
      "seasons",
    ],
  },
  {
    id: "monsoon_pattern",
    kind: "risk",
    label: "monsoon pattern",
    aliases: [
      "monsoon pattern",
      "monsoon rains",
      "monsoon season",
      "southwest monsoon",
      "northeast monsoon",
      "monsoonal",
      "wet season",
      "rainy season",
      "summer monsoon",
      "monsoon",
    ],
  },
  {
    id: "wildfire_risk",
    kind: "risk",
    label: "wildfire risk",
    aliases: [
      "wildfire risk",
      "wildfire danger",
      "bushfire risk",
      "bush fire",
      "bushfire",
      "bushfires",
      "forest fire",
      "forest fires",
      "grass fire",
      "grassfire",
      "brush fire",
      "brushfire",
      "wild land fire",
      "wildland fire",
      "fire weather",
      "fire risk",
      "fire season",
      "megafire",
      "wildfire",
      "wildfires",
      "fire",
    ],
  },
  {
    id: "storm_risk",
    kind: "risk",
    label: "storm risk",
    aliases: [
      "storm risk",
      "severe storm",
      "severe storms",
      "severe weather",
      "tropical cyclone",
      "tropical storm",
      "tropical storms",
      "extratropical storm",
      "winter storm",
      "thunderstorm",
      "thunderstorms",
      "thunder storm",
      "electrical storm",
      "hailstorm",
      "hail storm",
      "hail",
      "damaging winds",
      "high winds",
      "windstorm",
      "wind storm",
      "gale",
      "gales",
      "squall",
      "squalls",
      "tornado",
      "tornadoes",
      "twister",
      "twisters",
      "hurricane",
      "hurricanes",
      "typhoon",
      "typhoons",
      "cyclone",
      "cyclones",
      "super typhoon",
      "storm",
      "storms",
    ],
  },
  {
    id: "landslide_risk",
    kind: "risk",
    label: "landslide risk",
    aliases: [
      "landslide risk",
      "landslide hazard",
      "mudslide",
      "mudslides",
      "mud slide",
      "mudflow",
      "mud flow",
      "debris flow",
      "debris flows",
      "rockslide",
      "rock slide",
      "rockfall",
      "rock fall",
      "slope failure",
      "slope failures",
      "landslip",
      "landslip risk",
      "avalanche",
      "avalanches",
      "lahar",
      "lahars",
      "landslide",
      "landslides",
    ],
  },
  {
    id: "tropical",
    kind: "fact",
    label: "tropical",
    aliases: [
      "tropical climate",
      "tropical rainforest",
      "rainforest climate",
      "equatorial climate",
      "equatorial",
      "tropics",
      "tropical",
    ],
  },
  {
    id: "subtropical",
    kind: "fact",
    label: "subtropical",
    aliases: [
      "subtropical climate",
      "sub-tropical",
      "sub tropics",
      "subtropics",
      "subtropical",
    ],
  },
  {
    id: "temperate",
    kind: "fact",
    label: "temperate",
    aliases: [
      "temperate climate",
      "mild climate",
      "moderate climate",
      "temperate",
      "mild",
    ],
  },
  {
    id: "continental",
    kind: "fact",
    label: "continental",
    aliases: [
      "continental climate",
      "inland climate",
      "inland",
      "continental",
    ],
  },
  {
    id: "polar",
    kind: "fact",
    label: "polar",
    aliases: [
      "polar climate",
      "arctic climate",
      "subarctic",
      "sub-arctic",
      "tundra climate",
      "tundra",
      "polar",
      "arctic",
      "antarctica",
      "antarctic",
    ],
  },
  {
    id: "arid",
    kind: "fact",
    label: "arid",
    aliases: [
      "arid climate",
      "desert climate",
      "desert",
      "deserts",
      "hyper arid",
      "hyperarid",
      "arid",
    ],
  },
  {
    id: "semi_arid",
    kind: "fact",
    label: "semi-arid",
    aliases: [
      "semi-arid",
      "semiarid",
      "semi arid",
      "steppe climate",
      "steppe",
      "sahel",
    ],
  },
  {
    id: "humid",
    kind: "fact",
    label: "humid",
    aliases: [
      "humid climate",
      "high humidity",
      "muggy",
      "sticky weather",
      "moist climate",
      "moist",
      "humidity",
      "humid",
      "damp",
    ],
  },
  {
    id: "mediterranean",
    kind: "fact",
    label: "mediterranean",
    aliases: [
      "mediterranean climate",
      "med climate",
      "dry summer climate",
      "mediterranean",
    ],
  },
  {
    id: "oceanic",
    kind: "fact",
    label: "oceanic",
    aliases: [
      "oceanic climate",
      "maritime climate",
      "coastal climate",
      "marine climate",
      "maritime",
      "oceanic",
      "coastal",
    ],
  },
  {
    id: "warming_hotspot",
    kind: "fact",
    label: "warming hotspot",
    aliases: [
      "warming hotspot",
      "heat hotspot",
      "climate hotspot",
      "rapid warming",
      "fast warming",
      "warming risk",
      "temperature rise",
      "rising temperatures",
      "climate warming",
      "global warming",
      "climate change",
      "warming",
    ],
  },
  {
    id: "earthquake",
    kind: "hazard",
    label: "earthquake",
    aliases: [
      "earthquake risk",
      "earthquake hazard",
      "seismic risk",
      "seismic hazard",
      "seismic zone",
      "seismic activity",
      "earthquake zone",
      "fault line",
      "fault zone",
      "tremor",
      "tremors",
      "quake",
      "quakes",
      "earthquakes",
      "earthquake",
      "seismic",
    ],
  },
  {
    id: "volcano",
    kind: "hazard",
    label: "volcano",
    aliases: [
      "volcanic risk",
      "volcanic hazard",
      "volcanic eruption",
      "volcanic ash",
      "ashfall",
      "ash fall",
      "lava flow",
      "lava flows",
      "eruption",
      "eruptions",
      "volcanoes",
      "volcanic",
      "volcano",
    ],
  },
  {
    id: "tsunami",
    kind: "hazard",
    label: "tsunami",
    aliases: [
      "tsunami risk",
      "tsunami hazard",
      "tidal wave",
      "seismic sea wave",
      "tsunamis",
      "tsunami",
    ],
  },
  {
    id: "dust_storm",
    kind: "hazard",
    label: "dust storm",
    aliases: [
      "dust storm",
      "dust storms",
      "sandstorm",
      "sand storm",
      "sandstorms",
      "haboob",
      "haboobs",
      "dust devil",
      "blowing dust",
      "dust",
    ],
  },
  {
    id: "storm_surge",
    kind: "hazard",
    label: "storm surge",
    aliases: [
      "storm surge",
      "coastal surge",
      "surge flooding",
      "coastal inundation",
      "storm tide",
    ],
  },
  {
    id: "coastal_erosion",
    kind: "hazard",
    label: "coastal erosion",
    aliases: [
      "coastal erosion",
      "shoreline erosion",
      "beach erosion",
      "coastal retreat",
      "eroding coast",
      "sea level rise",
      "sea-level rise",
      "rising seas",
      "coastal flooding",
    ],
  },
];

export type QuestionPattern = {
  id: string;
  /** Regex matched against the normalized query. */
  pattern: RegExp;
  intent:
    | "similar_to"
    | "trait_search"
    | "compare"
    | "city_lookup"
    | "explain_city";
};

/**
 * Ordered from more specific question shapes to broader ones.
 * Capturing groups are interpreted by the parser.
 */
export const QUESTION_PATTERNS: QuestionPattern[] = [
  {
    id: "compare_cities",
    pattern:
      /\b(?:compare|vs\.?|versus|difference between|differ between)\b/,
    intent: "compare",
  },
  {
    id: "similar_to_city",
    pattern:
      /\b(?:similar(?:\s+cities)?\s+to|cities\s+like|like|climate\s+like|similar\s+climate\s+to|resemble|resembles)\b/,
    intent: "similar_to",
  },
  {
    id: "explain_city",
    pattern:
      /\b(?:what(?:'s| is) the climate(?: like)?(?: in| of)?|climate(?: profile)?(?: of| in)|tell me about|describe)\b/,
    intent: "explain_city",
  },
  {
    id: "which_cities_traits",
    pattern:
      /\b(?:which|what|show|find|list|where(?:\s+are)?)\b.*\b(?:cities|city|places|regions)\b/,
    intent: "trait_search",
  },
  {
    id: "cities_with_traits",
    pattern:
      /\b(?:cities|places)\s+(?:with|that have|facing|at risk of|at risk from|prone to|vulnerable to)\b/,
    intent: "trait_search",
  },
  {
    id: "hazard_search",
    pattern:
      /\b(?:flood|rain|hail|drought|heat|cold|wildfire|bushfire|hurricane|typhoon|cyclone|tornado|earthquake|volcano|tsunami|mudslide|landslide|monsoon|storm)\b/,
    intent: "trait_search",
  },
];

/** Filler words stripped before city / term extraction. */
export const STOP_PHRASES = [
  "please",
  "show me",
  "show",
  "find me",
  "find",
  "list",
  "which cities",
  "which city",
  "what cities",
  "what city",
  "cities that have",
  "cities with",
  "cities like",
  "places with",
  "places like",
  "places prone to",
  "cities prone to",
  "prone to",
  "vulnerable to",
  "similar to",
  "similar cities to",
  "climate like",
  "climate of",
  "climate in",
  "climate profile of",
  "climate profile in",
  "what's the climate like in",
  "whats the climate like in",
  "what is the climate like in",
  "what is the climate in",
  "what is the climate of",
  "tell me about",
  "describe",
  "compare",
  "versus",
  "vs",
  "difference between",
  "differ between",
  "and",
  "or",
  "the",
  "a",
  "an",
  "of",
  "in",
  "to",
  "for",
  "with",
  "that have",
  "facing",
  "at risk of",
  "at risk from",
  "risk",
  "risks",
  "hazard",
  "hazards",
  "climate",
  "weather",
] as const;

/** Short aliases that are allowed despite length < 3. */
export const SHORT_ALIAS_ALLOWLIST = new Set(["hot", "dry", "wet", "ice"]);
